######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 6 17:22:20 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . attic tests/hardlines
INCLUDEPATH += . /usr/include

LIBS += -lGL

QT += opengl
CONFIG += thread

# Input
HEADERS = mainwindow.h GLvideo.h GLvideo_mt.h GLvideo_rt.h
SOURCES = main.cpp mainwindow.cpp GLvideo.cpp GLvideo_mt.cpp GLvideo_rt.cpp
